---
title: "Sample Figures"
author: "Ryan Sheridan"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 3
    df_print: "paged"
    code_folding: "hide"
    self_contained: true
    highlight: "kate"
params:
  genome: "GRCm"
  template_dir: "../../src"
  rds_dir: "../../sobjs/so"
  fig3_sobjs:
    value:
      - ["d2_so.rds", "DC", "Myeloid Cells (Day 2)"]
      - ["d14_so.rds", "DC", "Myeloid Cells (Day 14)"]
      - ["d14_so.rds", "LEC", "Endothelial/Stromal Cells (Day 14)"]
      - ["d14_so.rds", "fibroblast", "Fibroblast/Stromal Cells (Day 14)"]
  corr_sobjs:
    value:
      - ["d2_so.rds", "DC", "Myeloid Cells (Day 2)"]
      - ["d14_so.rds", "DC", "Myeloid Cells (Day 14)"]
      - ["d2_so.rds", "LEC", "Endothelial/Stromal Cells (Day 2)"]
      - ["d14_so.rds", "LEC", "Endothelial/Stromal Cells (Day 14)"]
      - ["d2_so.rds", "fibroblast", "Fibroblast/Stromal Cells (Day 2)"]
      - ["d14_so.rds", "fibroblast", "Fibroblast/Stromal Cells (Day 14)"]
editor_options: 
  chunk_output_type: console
---

---

`r knitr::knit_child(file.path(params$template_dir, "funs.Rmd"))`

```{r "Plotting functions", echo = F}

# Add one to variable
plus_one <- function(x, n = 1) {
  cmd <- str_c(x, " <<- ", x, " + ", n)
  
  eval(parse(text = cmd))
  eval(parse(text = x))
}

# Set colors
set_cols <- function(types_in, cols_in, other_cols) {
  
  types_in <- types_in[!types_in %in% names(other_cols)]
  cols_in <- cols_in[!cols_in %in% other_cols]
  
  names(cols_in) <- types_in
  cols_in <- cols_in[!is.na(names(cols_in))]
  
  res <- c(cols_in, other_cols)
  
  res
}

# Set subtype colors
set_type_cols <- function(sobjs_in, type_column = "cell_type2", cols_in, other_cols) {
  
  res <- sobjs_in %>%
    map(~ {
      .x@meta.data %>%
        pull(type_column) %>%
        unique()
    }) %>%
    reduce(c) %>%
    unique() %>%
    set_cols(
      cols_in = cols_in,
      other_cols = other_cols
    )
  
  res
}

# Capitalize first character without modifying other characters
str_to_title_v2 <- function(string) {
  
  cap_first_chr <- function(string) {
    chrs <- string %>%
      str_split(pattern = "") %>%
      unlist()
    
    if (any(chrs %in% LETTERS)) {
      return(string)
    }
    
    chrs[1] <- str_to_upper(chrs[1])
    
    res <- chrs %>%
      reduce(str_c)
    
    res
  }
  
  res <- string %>%
    map_chr(~ {
      .x %>%
        str_split(pattern = " ") %>%
        unlist() %>%
        map_chr(cap_first_chr) %>%
        reduce(str_c, sep = " ")
    })
  
  res
}

# Subset Seurat objects for plotting
subset_sobj <- function(sobj_in, type, type_column = "cell_type1", subtype_column = "cell_type2",
                        min_cells = 15, include_types = c("B cell", "T cell", "epithelial"),
                        orig_idents = c("_1" = "CD45_neg", "_2" = "CD45_pos"),
                        type_filt = c("DC" = "CD45_pos", "LEC" = "CD45_neg", "fibroblast" = "CD45_neg"),
                        cap_names = T, ...) {
  
  res <- sobj_in

  # Set orig.ident based on cell_id
  if (!is.null(orig_idents)) {
    res@meta.data <- res@meta.data %>%
      rownames_to_column("cell_id") %>%
      mutate(
        orig.ident = str_extract(cell_id, "_[0-9]+$"),
        orig.ident = orig_idents[orig.ident]
      ) %>%
      column_to_rownames("cell_id")
  }
  
  # Filter cells based on orig.ident
  if (!is.null(type_filt)) {
    res <- res %>%
      subset(subset = orig.ident == type_filt[type])
  }
  
  # Filter cells based on input cell type
  res <- res %>%
    subset(subset = !!sym(type_column) %in% c(type, include_types))
  
  if (!type %in% pull(res@meta.data, type_column)) {
    stop(str_c("ERROR: Cell type not present after filtering for ", CD45_status))
  }
  
  # Filter cells based on number of cells per subtype
  if (!is.null(min_cells)) {
    keep_cells <- res@meta.data %>%
      rownames_to_column("cell_id") %>%
      group_by(!!sym(subtype_column)) %>%
      filter(n_distinct(cell_id) > min_cells) %>%
      pull(cell_id)
    
    res <- res %>%
      subset(cells = keep_cells)
  }
  
  # Capitalize subtypes
  if (cap_names) {
    res@meta.data <- res@meta.data %>%
      rownames_to_column("cell_id") %>%
      mutate(!!sym(subtype_column) := str_to_title_v2(!!sym(subtype_column))) %>%
      column_to_rownames("cell_id")
  }
  
  # Re-run UMAP
  res <- res %>%
    cluster_RNA(...)

  res
}

# Add arrows to axis
add_arrow_axis <- function(gg_in, fract = 0.1, ...) {
  
  get_line_coords <- function(range_in, fract) {
    mn  <- range_in[1]
    mx  <- range_in[2]
    dif <- mx - mn

    res <- c(mn - (dif * 0.05), mn + (dif * fract))

    res
  }
  
  x_coords <- ggplot_build(gg_in)$layout$panel_scales_x[[1]]$range$range %>%
    get_line_coords(fract = fract)

  y_coords <- ggplot_build(gg_in)$layout$panel_scales_y[[1]]$range$range %>%
    get_line_coords(fract = fract)
   
  res <- gg_in +
    geom_segment(
      x        = x_coords[1],
      xend     = x_coords[2], 
      y        = y_coords[1], 
      yend     = y_coords[1],
      size     = 0.25,
      color    = "black",
      linejoin = "bevel",
      arrow    = arrow(ends = "last", type = "open", length = unit(0.02, "npc")),
      ...
    ) +
    geom_segment(
      y        = y_coords[1], 
      yend     = y_coords[2], 
      x        = x_coords[1], 
      xend     = x_coords[1], 
      size     = 0.25,
      color    = "black",
      linejoin = "bevel",
      arrow    = arrow(ends = "last", type = "open", length = unit(0.02, "npc")),
      ...
    ) +
    theme(axis.title = element_text(hjust = 0, size = 10))
  
  res
}

# Set equal x-axis scales
equalize_x <- function(gg_list_in, log_tran = T, ...) {
  
  set_lims <- function(gg_in, min_x, max_x, log_tran, ...) {
    res <- gg_in +
      coord_cartesian(xlim = c(min_x, max_x))
    
    if (log_tran) {
      res$labels$x <- str_c(res$labels$x, " (log10)")
      
      res <- res +
        scale_x_log10(labels = trans_format("log10", math_format(10^.x)), ...)
    }
    
    res
  }
  
  gg_ranges <- gg_list_in %>%
    map(~ ggplot_build(.x)$layout$panel_scales_x[[1]]$range$range)
  
  min_val <- gg_ranges %>%
    map_dbl(~ .x[1]) %>%
    min()
  
  max_val <- gg_ranges %>%
    map_dbl(~ .x[2]) %>%
    max()
  
  res <- gg_list_in %>%
    map(
      set_lims,
      min_x    = min_val, 
      max_x    = max_val, 
      log_tran = log_tran,
      ...
    )
  
  res
}

# Function to create figure panel
create_fig3 <- function(sobj_in, cols_in, subtype_column = "cell_type2", pseudo = 0.03, data_slot = "counts",
                        box_counts = c("Fold-change relative to T/B cell abundance" = "ova_fc"), 
                        umap_counts = c("ova counts" = "adt_ovalbumin"), plot_title = NULL, arrow_axis = F, 
                        pt_size = 0.1, pt_outline = 0.4, umap_cell_count = F, box_cell_count = T,
                        control_types = c("B Cell", "T Cell"), ...) {
  
  box_column <- umap_column <- "cell_type"
  box_cols <- umap_cols <- cols_in
  
  # Fetch plotting data
  data_df <- sobj_in %>%
    FetchData(c(subtype_column, box_counts, umap_counts, "UMAP_1", "UMAP_2"), slot = data_slot) %>%
    as_tibble(rownames = "cell_id")
  
  # Add pseudo count
  if (0 %in% pull(data_df, box_counts)) {
    data_df <- data_df %>%
      mutate(
        pseudo = ifelse(!!sym(box_counts) > 0, !!sym(box_counts), NA),
        pseudo = min(pseudo, na.rm = T) * 0.5,
        !!sym(box_counts) := !!sym(box_counts) + pseudo
      )
  }
  
  if (!is.null(names(box_counts))) {
    data_df <- data_df %>%
      rename(!!box_counts)
    
    box_counts <- names(box_counts)
  }
  
  if (!is.null(names(umap_counts))) {
    data_df <- data_df %>%
      rename(!!umap_counts)
    
    umap_counts <- names(umap_counts)
  }
  
  # Set subtype order
  # Move select cell types to front of order
  data_df <- data_df %>%
    mutate(
      cell_type = !!sym(subtype_column),
      cell_type = fct_reorder(cell_type, !!sym(box_counts), median)
    )
  
  type_order <- levels(data_df$cell_type)
  
  if (!is.null(control_types)) {
    control_types <- control_types[control_types %in% type_order]
    type_order <- type_order[!type_order %in% control_types]
    type_order <- c(control_types, type_order)
  }
  
  # Count cells for each subtype
  data_df <- data_df %>%
    group_by(cell_type) %>%
    mutate(cell_count = n_distinct(cell_id)) %>%
    ungroup() %>%
    mutate(cell_type = fct_relevel(cell_type, type_order)) %>%
    arrange(cell_type) %>%
    mutate(
      cell_count = str_c(cell_type, "\n(n = ", cell_count, ")"),
      cell_count = fct_inorder(cell_count)
    )
  
  # Set cell type colors
  names(type_order) <- levels(data_df$cell_count)
  
  cols_df <- tibble(
    cell_type = type_order,
    cell_count = names(type_order)
  )
  
  cols_df <- cols_df %>%
    mutate(color = cols_in[cell_type])
  
  # Subtype UMAP
  if (umap_cell_count) {
    umap_column <- "cell_count"
    umap_cols <- setNames(cols_df$color, cols_df$cell_count)
  }
  
  umap <- data_df %>%
    plot_features(
      feature     = umap_column,
      pt_size     = pt_size,
      pt_outline  = pt_outline,
      plot_cols   = umap_cols,
      feat_levels = rev(names(umap_cols))
    ) +
    guides(color = guide_legend(override.aes = list(size = 3.5))) +
    ggtitle(plot_title) +
    blank_theme +
    theme(
      plot.title = element_text(size = 12),
      legend.position = "none"
    ) +
    theme(...)
  
  if (arrow_axis) {
    umap <- add_arrow_axis(umap)
  }
  
  # OVA UMAP
  if (!is.null(umap_counts)) {
    ova_umap <- data_df %>%
      plot_features(
        feature    = umap_counts,
        plot_cols  = c("#fafafa", "#d7301f"),
        pt_size    = 0.3,
        pt_outline = 0.5,
        min_pct    = 0.01,
        max_pct    = 0.99
      ) +
      blank_theme +
      theme(
        plot.title        = element_text(size = 10, hjust = 0.5),
        legend.position   = "right",
        legend.key.width  = unit(0.15, "cm"),
        legend.key.height = unit(0.30, "cm"),
        legend.title      = element_text(size = 10),
        legend.text       = element_text(size = 10)
      )
    
    if (arrow_axis) {
      ova_umap <- add_arrow_axis(ova_umap)
    }
  }
  
  # OVA boxes
  if (box_cell_count) {
    box_column <- "cell_count"
    box_cols <- setNames(cols_df$color, cols_df$cell_count)
  }
  
  boxes <- data_df %>%
    ggplot(aes(!!sym(box_counts), !!sym(box_column), fill = !!sym(box_column))) +
    geom_violin(size = 0.3, draw_quantiles = c(0.25, 0.75), alpha = 0.75) +
    stat_summary(geom = "point", color = "black", fun = median) +
    scale_color_manual(values = box_cols) +
    scale_fill_manual(values = box_cols) +
    theme_minimal_vgrid() +
    theme(
      legend.position    = "none",
      axis.title.y       = element_blank(),
      axis.title         = element_text(size = 10),
      axis.text          = element_text(size = 10),
      axis.ticks.x       = element_line(size = 0.1),
      panel.grid.major.x = element_line(size = 0.1)
    )
  
  res <- list(umap, boxes)
  
  if (!is.null(umap_counts)) {
    res <- append(res, list(ova_umap))
  }
  
  res
}

# Plot correlation
plot_corr <- function(sobj_in, x, y, feat, data_slot, cols_in, plot_title, ...) {
  res <- sobj_in %>%
    FetchData(c(x, y, feat), slot = data_slot) %>%
    mutate(
      !!sym(x) := log10(!!sym(x)),
      !!sym(y) := log10(!!sym(y))
    ) %>%
    filter(
      !!sym(x) != -Inf,
      !!sym(y) != -Inf
    ) %>%
    plot_features(
      x         = x,
      y         = y,
      feature   = feat,
      data_slot = "counts",
      plot_cols = cols_in,
      calc_cor  = T,
      lm_line   = T,
      ...
    ) +
    ggtitle(plot_title) +
    guides(color = guide_legend(override.aes = list(size = 3.5))) +
    theme_info +
    theme(legend.title = element_blank())
  
  res
}

```

```{r "Load data", echo = F}

# Load Seurat objects
# Avoid loading/clustering same objects twice
so_info <- append(params$fig3_sobjs, params$corr_sobjs) %>%
  unique()

so_types <- map_chr(so_info, ~ .x[2])
so_names <- map_chr(so_info, ~ .x[3])
so_paths <- map_chr(so_info, ~ .x[1])

sobjs <- unique(so_paths) %>%
  setNames(., .) %>%
  map(~ read_rds(file.path(params$rds_dir, .x)))

# Subset objects based on cell types
# Avoid loading/clustering same objects twice
sobjs <- sobjs[match(so_paths, names(sobjs))]
sobjs_sub <- map2(sobjs, so_types, subset_sobj)
names(sobjs_sub) <- so_names

# Split sobjs for figures
fig3_names <- params$fig3_sobjs %>%
  map_chr(~ .x[3])

corr_names <- params$corr_sobjs %>%
  map_chr(~ .x[3])

fig3_sobjs <- sobjs_sub[fig3_names]
corr_sobjs <- sobjs_sub[corr_names]

# Color palettes
common_cols <- c(
  "Epithelial" = "#6a51a3",
  "B Cell" = "#E69F00",
  "T Cell" = "#009E73"
)

DC_cols <- sobjs_sub[so_types == "DC"] %>%
  set_type_cols(
    cols_in = ito_cols,
    other_cols = common_cols
  )

LEC_cols <- sobjs_sub[so_types == "LEC"] %>%
  set_type_cols(
    cols_in = ito_cols,
    other_cols = common_cols
  )
  
FRC_cols <- sobjs_sub[so_types == "fibroblast"] %>%
  set_type_cols(
    cols_in = ito_cols,
    other_cols = common_cols
  )

# Parameter lists
fig3_params <- list(
  sobj_in    = fig3_sobjs, 
  plot_title = names(fig3_sobjs), 
  cols_in    = list(DC_cols, DC_cols, LEC_cols, FRC_cols)
)

corr_params <- list(
  sobj_in    = corr_sobjs, 
  plot_title = names(corr_sobjs), 
  cols_in    = list(DC_cols, DC_cols, LEC_cols, LEC_cols, FRC_cols, FRC_cols)
)

n_plot <- 0

```

```{r, ref.label = c("Plotting functions", "Load data"), eval = F}
```

## Figure 3

```{r, fig.width = 13, fig.height = 18}

# Create panel plots
gg_list <- fig3_params %>%
  pmap(
    create_fig3,
    box_counts  = c("Fold-change relative to T/B cell abundance" = "ova_fc"), 
    umap_counts = c("ova counts" = "adt_ovalbumin"),
    data_slot   = "counts"
  ) %>%
  flatten()

# Set violin scales equal
violin_idx <- seq_along(gg_list) %% 3 == 2
gg_list[violin_idx] <- gg_list[violin_idx] %>%
  equalize_x()

# Create final figure
gg_list %>%
  wrap_plots(ncol = 3, widths = c(1, 0.75, 1)) +
  plot_annotation(tag_levels = "a") &
  theme(
    plot.margin = unit(c(1, 0.5, 0.5, 0.5), "cm"),
    plot.tag = element_text(size = 24, face = "plain"),
    plot.tag.position = c(-0.08, 1)
  )

```

---

<br>

<br>

## Supplemental `r plus_one("n_plot")`

```{r, fig.width = 13, fig.height = 18}

# New names and colors
new_names <- c(
  "cLEC" = "Ceiling LECs",
  "fLEC" = "Floor LECs"
)

new_cols <- LEC_cols <- c(
  LEC_cols,
  "Ptx3_LEC" = "#D55E00",
  "Unassigned" = "#ffffff"
)

# Assign cell types with new reference
load("../../clustifyr/ref_LEC_xiang.rda")

new_sobjs <- sobjs_sub

new_sobjs[so_types == "LEC"] <- new_sobjs[so_types == "LEC"] %>%
  map(
    clustify, 
    ref_mat = ref_LEC_xiang, 
    cluster_col = "RNA_clusters"
  ) %>%
  map(~ {
    .x@meta.data <- .x@meta.data %>%
      rownames_to_column("cell_id") %>%
      mutate(
        new_types  = if_else(type %in% names(new_names), new_names[type], type),
        new_types  = str_to_title_v2(new_types),
        old_types  = cell_type2,
        cell_type2 = new_types
      ) %>%
      column_to_rownames("cell_id")
    .x
  })

new_sobjs <- new_sobjs[fig3_names]

# Figure parameters
LEC_params <- list(
  sobj_in    = new_sobjs,
  plot_title = names(new_sobjs),
  cols_in    = list(DC_cols, DC_cols, new_cols, FRC_cols)
)

# Create panel plots
gg_list <- LEC_params %>%
  pmap(
    create_fig3,
    box_counts  = c("Fold-change relative to T/B cell abundance" = "ova_fc"), 
    umap_counts = c("ova counts" = "adt_ovalbumin"),
    data_slot   = "counts"
  ) %>%
  flatten()

# Set violin scales equal
violin_idx <- seq_along(gg_list) %% 3 == 2
gg_list[violin_idx] <- gg_list[violin_idx] %>%
  equalize_x()

# Create final figure
gg_list %>%
  wrap_plots(ncol = 3, widths = c(1, 0.75, 1)) +
  plot_annotation(tag_levels = "a") &
  theme(
    plot.margin = unit(c(1, 0.5, 0.5, 0.5), "cm"),
    plot.tag = element_text(size = 24, face = "plain"),
    plot.tag.position = c(-0.08, 1)
  )

```

---

<br>

<br>

## Supplemental `r plus_one("n_plot")`

```{r, fig.width = 15, fig.height = 15}

corr_params %>%
  pmap(
    plot_corr,
    x         = c("RNA counts (log10)" = "nCount_RNA"),
    y         = c("ova counts (log10)" = "adt_ovalbumin"),
    feat      = "cell_type2",
    data_slot = "counts",
    pt_size   = 0.5
  ) %>%
  plot_grid(
    plotlist = .,
    ncol     = 2,
    align    = "vh",
    axis     = "trbl"
  )

```

---

<br>

<br>

## Supplemental `r plus_one("n_plot")`

```{r, fig.width = 20, fig.height = 33}

pad <- c(2, 2, 9, 2, 9.5, 2)

corr_params %>%
  pmap(
    plot_corr,
    x         = c("RNA counts (log10)" = "nCount_RNA"),
    y         = c("ova counts (log10)" = "adt_ovalbumin"),
    feat      = "cell_type2",
    split_id  = "cell_type2",
    data_slot = "counts",
    pt_size   = 1,
    scales    = "free",
    ncol      = 3
  ) %>%
  map2(pad, ~ {
    .x + theme(
      legend.position = "none",
      plot.margin = unit(c(0.2, 0.2, .y, 0.2), "cm")
    )
  }) %>%
  plot_grid(
    plotlist = .,
    rel_heights = c(1, 1.2, 1),
    align = "v",
    ncol = 2
  )

```

---

<br>

<br>

## Supplemental `r plus_one("n_plot")`

```{r, fig.width = 8, fig.height = 6}

calc_type_cor <- function(sobj_in, ..., assay = "RNA") {
  
  calc_type_expr <- function(sobj_in, column, prefix, assay) {
    
    cell_types <- sobj_in@meta.data %>%
      pull(!!sym(column)) %>%
      unique()
    
    names(cell_types) <- str_c(prefix, cell_types)
    
    res <- cell_types %>%
      map(~ {
        ids <- sobj_in@meta.data %>%
          as_tibble(rownames = "cell_id") %>%
          filter(!!sym(column) == .x) %>%
          pull(cell_id)
        
        sobj_in %>%
          GetAssayData(assay = assay, slot = "data") %>%
          .[, ids] %>%
          as.matrix() %>%
          rowMeans()
      })
    
    res
  }
  
  columns <- list(...)
  
  expr_vecs <- columns %>%
    imap(~ calc_type_expr(
      sobj_in = sobj_in,
      column  = .x,
      prefix  = str_c(.y, "_"),
      assay   = assay
    ))
  
  res <- expr_vecs %>%
    flatten() %>%
    do.call(cbind, .) %>%
    cor() %>%
    round(2)
  
  res
}

LEC_so <- new_sobjs$`Endothelial/Stromal Cells (Day 14)`

cor_mat <- LEC_so %>%
  calc_type_cor("old_types", "new_types")

Heatmap(cor_mat)

```

