---
title: "Sample Figures"
author: "Ryan Sheridan"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 3
    df_print: "paged"
    code_folding: "hide"
    self_contained: true
    highlight: "kate"
params:
  genome: "GRCm"
  template_dir: "../src"
  rds_dir: "../sobjs/so"
  sobjs:
    value:
      - ["d2_so.rds", "DC", "d2 DC"]
      - ["d14_so.rds", "DC", "d14 DC"]
      - ["d14_so.rds", "LEC", "d14 LEC"]
      - ["d14_so.rds", "fibroblast", "d14 FRC"]
---

---

`r knitr::knit_child(file.path(params$template_dir, "funs.Rmd"))`

```{r "Setup", echo = F}

# Function to subset Seurat objects for plotting
subset_sobj <- function(sobj_path, type, type_column = "cell_type1", ...) {
  res <- sobj_path %>%
    file.path(params$rds_dir, .) %>%
    read_rds() %>%
    subset(subset = !!sym(type_column) %in% c(type, "B cell", "T cell")) %>%
    cluster_RNA(...)
  
  res
}

# Function to add arrows to axis
add_arrow_axis <- function(gg_in, fract = 0.1, ...) {
  
  get_line_coords <- function(range_in, fract) {
    mn  <- range_in[1]
    mx  <- range_in[2]
    dif <- mx - mn

    res <- c(mn - (dif * 0.05), mn + (dif * fract))

    res
  }
  
  x_coords <- ggplot_build(gg_in)$layout$panel_scales_x[[1]]$range$range %>%
    get_line_coords(fract = fract)

  y_coords <- ggplot_build(gg_in)$layout$panel_scales_y[[1]]$range$range %>%
    get_line_coords(fract = fract)
   
  res <- gg_in +
    geom_segment(
      x        = x_coords[1],
      xend     = x_coords[2], 
      y        = y_coords[1], 
      yend     = y_coords[1],
      size     = 0.25,
      color    = "black",
      linejoin = "bevel",
      arrow    = arrow(ends = "last", type = "open", length = unit(0.02, "npc")),
      ...
    ) +
    geom_segment(
      y        = y_coords[1], 
      yend     = y_coords[2], 
      x        = x_coords[1], 
      xend     = x_coords[1], 
      size     = 0.25,
      color    = "black",
      linejoin = "bevel",
      arrow    = arrow(ends = "last", type = "open", length = unit(0.02, "npc")),
      ...
    ) +
    theme(axis.title = element_text(hjust = 0, size = 10))
  
  res
}

# Function to create figure panel
create_fig <- function(sobj_in, cols_in, type_column = "cell_type2",
                       data_column = "ova_fc", title = NULL, gg_out = NULL,
                       legd_rows = 10, arrow_axis = F, pt_size = 0.1, pt_outline = 0.4, ...) {
  
  if (!is.null(gg_out) && !exists(gg_out)) {
    cmd <- str_c(gg_out, " <<- NULL")
    eval(parse(text = cmd))
  }
  
  # Multipliers to adjust UMAP point size based on number of cells
  mtplyr_1 <- if_else(ncol(sobj_in) < 500, 3, 1)
  mtplyr_2 <- if_else(ncol(sobj_in) < 500, 6, 1)
  mtplyr_3 <- if_else(ncol(sobj_in) < 500, mtplyr_2 * 2.5, 1)
  
  # Set subtype colors
  if (is.null(names(cols_in))) {
    cell_types <- sobj_in@meta.data %>%
      pull(type_column) %>%
      unique()
    
    cell_types <- cell_types[!cell_types %in% c("B cell", "T cell")]
    names(cell_types) <- cell_types
    
    cols_in <- cols_in[!cols_in %in% c("#E69F00", "#009E73")]
    names(cols_in) <- cell_types
    cols_in <- cols_in[!is.na(names(cols_in))]
    
    cols_in <- c(
      cols_in,
      "B cell" = "#E69F00",
      "T cell" = "#009E73"
    )
  }
  
  # Subtype UMAP
  umap <- sobj_in %>%
    plot_features(
      feature     = type_column,
      pt_size     = pt_size * mtplyr_3,
      pt_outline  = pt_outline,
      plot_cols   = cols_in,
      feat_levels = names(cols_in)
    ) +
    guides(color = guide_legend(override.aes = list(size = 3.5), nrow = legd_rows)) +
    blank_theme +
    theme(
      legend.title = element_blank(),
      legend.text  = element_text(size = 10),
      ...
    )
  
  if (arrow_axis) {
    umap <- add_arrow_axis(umap)
  }
  
  # if (!is.null(title)) {
  #   umap <- umap +
  #     ggtitle(title)
  #     # labs(tag = title)
  #     # labs(y = title) +
  #     # theme(axis.title.y = element_text(size = 20))
  # }
  
  # OVA boxes
  boxes <- sobj_in %>%
    create_ci_boxes(
      group_column = type_column, 
      data_column  = data_column, 
      box_cols     = cols_in,
      ...
    )
  
  if (!is.null(gg_out)) {
    umap_cmd <- str_c(gg_out, " <<- append(", gg_out, ", list('", title, "' = umap))")
    box_cmd <- str_c(gg_out, " <<- append(", gg_out, ", list(boxes))")
    
    eval(parse(text = umap_cmd))
    eval(parse(text = box_cmd))
    
    return(NULL)
  }
  
  res <- list(umap, boxes)
  
  res
}

# Setup list of sobj paths
so_names <- params$sobjs %>%
  map_chr(~ .x[2])

sobjs <- params$sobjs
names(sobjs) <- so_names 

sobjs <- sobjs %>%
  map_chr(~ .x[1])

sobjs <- sobjs %>%
  imap(subset_sobj)

```

## Version 1

```{r, fig.width = 10, fig.height = 17}

# DC colors
DC_sobjs <- sobjs[names(sobjs) == "DC"]
names(DC_sobjs) <- c("d2 DC", "d14 DC")

DC_types <- DC_sobjs %>%
  map(~ unique(.x$cell_type2)) %>%
  reduce(c) %>%
  unique()

DC_types <- DC_types[!DC_types %in% c("B cell", "T cell")]
DC_cols <- theme_cols[!theme_cols %in% c("#E69F00", "#009E73")]
names(DC_cols) <- DC_types
DC_cols <- DC_cols[!is.na(names(DC_cols))]

DC_cols <- c(
  DC_cols,
  "B cell" = "#E69F00",
  "T cell" = "#009E73"
)

# DC panels
rm(gg_list)

iwalk(DC_sobjs, ~ create_fig(
  sobj_in   = .x,
  cols_in   = DC_cols,
  title     = .y,
  gg_out    = "gg_list",
  legd_rows = 4,
  legend.position = "top"
))

# Other panels
other_sobjs <- sobjs[names(sobjs) != "DC"]

names(other_sobjs) <- names(other_sobjs) %>%
  str_replace("LEC", "d14 LEC") %>%
  str_replace("fibroblast", "d14 FRC")

iwalk(other_sobjs, ~ create_fig(
  sobj_in   = .x,
  cols_in   = theme_cols,
  title     = .y,
  gg_out    = "gg_list",
  legd_rows = 4,
  legend.position = "top"
))

# Create final figure
plot_grid(
  plotlist       = gg_list,
  labels         = names(gg_list),
  label_size     = 18,
  label_fontface = "plain",
  label_x        = -0.05,
  ncol           = 2,
  align          = "vh",
  axis           = "trbl"
)

```

---

<br>

<br>

## Version 2

```{r, fig.width = 10, fig.height = 17}

# DC panels
rm(gg_list)

iwalk(DC_sobjs, ~ create_fig(
  sobj_in    = .x,
  cols_in    = DC_cols,
  title      = .y,
  gg_out     = "gg_list",
  legend.position = "left"
))

# Other panels
iwalk(other_sobjs, ~ create_fig(
  sobj_in    = .x,
  cols_in    = theme_cols,
  title      = .y,
  gg_out     = "gg_list",
  legend.position = "left"
))

# Create final figure
plot_grid(
  plotlist       = gg_list,
  labels         = names(gg_list),
  label_size     = 18,
  label_fontface = "plain",
  label_x        = -0.05,
  ncol           = 2,
  align          = "vh",
  axis           = "trbl"
)

```

---

<br>

<br>

## Version 3

```{r, fig.width = 10, fig.height = 17}

# DC panels
rm(gg_list)

iwalk(DC_sobjs, ~ create_fig(
  sobj_in    = .x,
  cols_in    = DC_cols,
  title      = .y,
  gg_out     = "gg_list",
  arrow_axis = T,
  legend.position = "left"
))

# Other panels
iwalk(other_sobjs, ~ create_fig(
  sobj_in    = .x,
  cols_in    = theme_cols,
  title      = .y,
  gg_out     = "gg_list",
  arrow_axis = T,
  legend.position = "left"
))

# Create final figure
plot_grid(
  plotlist       = gg_list,
  labels         = names(gg_list),
  label_size     = 18,
  label_fontface = "plain",
  label_x        = -0.05,
  ncol           = 2,
  align          = "vh",
  axis           = "trbl"
)

```

---

<br>

<br>

## Version 4

```{r, fig.width = 12, fig.height = 17}

# DC panels
rm(gg_list)

iwalk(DC_sobjs, ~ create_fig(
  sobj_in = .x,
  cols_in = DC_cols,
  title   = .y,
  gg_out  = "gg_list",
  legend.position = "left",
  axis.line = element_line(size = 0.5, color = "black"),
  axis.title = element_text(size = 10)
))

# Other panels
iwalk(other_sobjs, ~ create_fig(
  sobj_in = .x,
  cols_in = theme_cols,
  title   = .y,
  gg_out  = "gg_list",
  legend.position = "left",
  axis.line = element_line(size = 0.5, color = "black"),
  axis.title = element_text(size = 10)
))

# Create final figure
plot_grid(
  plotlist       = gg_list,
  labels         = names(gg_list),
  label_size     = 20,
  label_fontface = "plain",
  ncol           = 2,
  align          = "vh",
  axis           = "trbl"
)

```

---

<br>

<br>

## Version 5

```{r, fig.width = 12, fig.height = 17}

# DC panels
rm(gg_list)

iwalk(DC_sobjs, ~ create_fig(
  sobj_in    = .x,
  cols_in    = DC_cols,
  title      = .y,
  gg_out     = "gg_list",
  pt_size    = 0.25,
  pt_outline = NULL,
  legend.position = "left"
))

# Other panels
other_sobjs <- sobjs[names(sobjs) != "DC"]

names(other_sobjs) <- names(other_sobjs) %>%
  str_replace("LEC", "d14 LEC") %>%
  str_replace("fibroblast", "d14 FRC")

iwalk(other_sobjs, ~ create_fig(
  sobj_in    = .x,
  cols_in    = theme_cols,
  title      = .y,
  gg_out     = "gg_list",
  pt_size    = 0.25,
  pt_outline = NULL,
  legend.position = "left"
))

# Create final figure
plot_grid(
  plotlist       = gg_list,
  labels         = names(gg_list),
  label_size     = 20,
  label_fontface = "plain",
  ncol           = 2,
  align          = "vh",
  axis           = "trbl"
)

```

```{r "EXTRAs", eval = F, echo = F}

# min_conf <- min(conf_df$lower)
# min_conf <- if_else(min_conf < 0, abs(min_conf), 0)
# conf_df <- conf_df %>%
#   mutate_if(.predicate = is.double, (function(x) x + min_conf + pseudo))
# box_data <- box_data %>%
#   mutate(!!sym(data_column) := !!sym(data_column) + min_conf + pseudo)

# conf_df %>%
#   mutate(conf = fct_relevel(conf, c("99%", "95%", "90%"))) %>%
#   pivot_longer(cols = c(-grp, -conf), names_to = "key", values_to = "val") %>% 
#   ggplot(aes(x = grp, y = val, fill = grp, alpha = conf)) + 
#   geom_boxplot(position = "identity", ymin = NA, ymax = NA, middle = NA) + 
#   scale_alpha_manual(values = c(0.125, 0.25, 1)) +
#   scale_fill_manual(values = theme_cols) +
#   theme_info
# 
# load_sobjs <- function(sobj_path, cell_type) {
#   
#   sobj <- read_rds(sobj_path)
#   
#   cell_type_id <- str_c("cell_type", cell_type)
#   
#   sobj@meta.data <- sobj@meta.data %>%
#     rownames_to_column("cell_id") %>%
#     mutate(cell_type = !!sym(cell_type_id)) %>%
#     column_to_rownames("cell_id")
#   
#   sobj
# }
# 
# rds_files <- names(params$subtypes) %>%
  # str_c(params$rds_dir, "/", .)
# 
# names(rds_files) <- names(params$subtypes)
# rds_types <- as.character(params$subtypes)
# 
# sobjs <- map2(rds_files, rds_types, load_sobjs)
# 
# rm(gg_list)
# walk(
#   .x = sobjs,
#   .f = create_fig,
#   cols_in = theme_cols,
#   gg_out  = "gg_list"
# )
# plot_grid(
#   plotlist = gg_list,
#   ncol     = 2,
#   align    = "vh",
#   axis     = "trbl"
# )
# 
# DCs
# DC_sobjs <- sobjs[names(sobjs) == "DC"]
# 
# DC_types <- DC_sobjs %>%
#   map(~ unique(.x$cell_type2)) %>%
#   reduce(c) %>%
#   unique()
# 
# DC_types <- DC_types[!DC_types %in% c("B cell", "T cell")]
# DC_cols <- theme_cols[!theme_cols %in% c("#E69F00", "#009E73")]
# names(DC_cols) <- DC_types
# DC_cols <- DC_cols[!is.na(names(DC_cols))]
# 
# DC_cols <- c(
#   DC_cols,
#   "B cell" = "#E69F00",
#   "T cell" = "#009E73"
# )
# 
# d2_DC <- DCs[[1]] %>%
#   create_fig(
#     cols_in = DC_cols,
#     title = "d2 DC",
#     legend.position = "top"
#   )
# 
# d2_DC <- DCs[[2]] %>%
#   create_fig(
#     cols_in = DC_cols,
#     title = "d14 DC",
#     legend.position = "none"
#   )
# 
# Other cells
# other_sobjs <- sobjs[names(sobjs) != "DC"]
# 
# names(other_sobjs) <- names(other_sobjs) %>%
#   str_replace("LEC", "d14 LEC") %>%
#   str_replace("fibroblast", "d14 FRC")
# 
# other_gg <- other_sobjs %>%
#   imap(~ create_fig(
#     sobj_in = .x,
#     cols_in = theme_cols,
#     title   = .y,
#     legend.position = "top"
#   )) %>%
#   flatten()
# 
# append(DCs_1, DCs_2) %>%
#   append(other_gg) %>%
#   plot_grid(
#     plotlist = .,
#     rel_heights = c(1, 0.8, 1, 1),
#     ncol     = 2,
#     align    = "v"
#   )

```
