
```{r "{{.x}} Setup", echo = F}

# Load Seurat object
rds_file <- "{{.x}}"
rds_name <- basename(rds_file)

sobj <- read_rds(rds_file)

```

## **`r rds_name`**

```{r "{{.x}} BOXES", echo = F}

# Set subtype order and colors
cell_types <- sobj@meta.data %>%
  pull(cell_type2) %>%
  unique()

names(cell_types) <- cell_types

type_cols <- c(theme_cols, theme_cols)[seq_along(cell_types)]
names(type_cols) <- cell_types
type_cols <- type_cols[!is.na(names(type_cols))]

# Format boxplot data
box_data <- sobj@meta.data %>%
  as_tibble(rownames = "cell_id") %>%
  dplyr::select(cell_id, cell_type1, cell_type2, cell_type3, ova_fc) %>%
  mutate(cell_type2 = fct_reorder(cell_type2, ova_fc))

# Swarms
gg1 <- box_data %>%
  ggplot(aes(cell_type2, ova_fc, color = cell_type2)) + 
  geom_quasirandom(size = 0.25) +
  scale_color_manual(values = type_cols) + 
  coord_flip() + 
  scale_y_log10() + 
  theme_info + 
  theme(
    legend.position = "none",
    axis.title.y = element_blank()
  )

# Violins
gg2 <- box_data %>%
  ggplot(aes(cell_type2, ova_fc, color = cell_type2, fill = cell_type2)) +
  geom_violin(size = 0.5) +
  stat_summary(fun = "median", geom = "point", shape = 22, size = 2, fill = "white") +
  scale_color_manual(values = type_cols) +
  scale_fill_manual(values = type_cols) +
  coord_flip() + 
  scale_y_log10() +
  theme_info + 
  theme(
    legend.position = "none",
    axis.title.y = element_blank()
  )

# Box plots
gg3 <- box_data %>%
  ggplot(aes(cell_type2, ova_fc, color = cell_type2)) +
  geom_quasirandom(size = 0.25, color = "#d9d9d9") +
  geom_boxplot(fill = NA, size = 1, outlier.size = 0.5, outlier.color = NA, width = 0.7, ymin = NA, ymax = NA, fatten = 1) +
  scale_color_manual(values = type_cols) +
  scale_fill_manual(values = type_cols) +
  coord_flip() + 
  scale_y_log10() + 
  theme_info + 
  theme(
    legend.position = "none",
    axis.title.y = element_blank()
  )

gg4 <- box_data %>%
  ggplot(aes(cell_type2, ova_fc, color = cell_type2, fill = cell_type2)) +
  geom_quasirandom(size = 0.25, color = "#d9d9d9") +
  geom_boxplot(size = 0, color = "white", outlier.shape = NA, width = 0.4, alpha = 0.5) +
  stat_summary(fun = "median", geom = "point", shape = 22, size = 4, stroke = 0.1) +
  scale_color_manual(values = type_cols) +
  scale_fill_manual(values = type_cols) +
  coord_flip() + 
  scale_y_log10() + 
  theme_info + 
  theme(
    legend.position = "none",
    axis.title.y = element_blank()
  )

gg5 <- box_data %>%
  ggplot(aes(cell_type2, ova_fc, color = cell_type2, fill = cell_type2)) +
  geom_quasirandom(size = 0.25, color = "#d9d9d9") +
  # geom_sina(size = 0.5, color = "#d9d9d9") +
  geom_boxplot(size = 1, outlier.shape = NA, width = 0, ymin = NA, ymax = NA) +
  stat_summary(fun = "median", geom = "point", shape = 22, size = 1.5) +
  scale_color_manual(values = type_cols) +
  scale_fill_manual(values = type_cols) +
  coord_flip() + 
  scale_y_log10() + 
  theme_info + 
  theme(
    legend.position = "none",
    axis.title.y = element_blank()
  )

```

```{r "{{.x}} BARS", echo = F}

# Create data.frame with confidence intervals
get_boots <- function(data_in, conf = c(0.9, 0.95, 0.99), ...) {
  
  get_ci <- function(conf, boot_in, ...) {
    
    res <- boot.ci(
      boot.out = boot_in,
      conf     = conf, 
      type     = "basic", 
      ...
    )
    
    res <- tibble(
      median = res$t0,
      conf   = str_c(conf * 100, "%"),
      lower  = res$basic[4],
      upper  = res$basic[5]
    )
    
    res
  }
  
  boot_obj <- boot(
    data = data_in,
    statistic = function(x, i) median(x[i]),
    R = 10000
  )
  
  names(conf) <- conf
  
  res <- conf %>%
    map(get_ci, boot_obj) %>%
    bind_rows()
  
  res
}

conf_df <- box_data %>%
  group_by(cell_type2) %>%
  summarize(boot_res = list(get_boots(ova_fc))) %>%
  unnest(cols = boot_res)

# Create scaled error bars
conf_sizes <- c(
  `90%` = 3,
  `95%` = 2,
  `99%` = 1
)

conf_alphas <- c(
  `90%` = 1,
  `95%` = 0.5,
  `99%` = 0.25
)

conf_df %>%
  ggplot(aes(`median`, cell_type2, color = cell_type2)) +
  geom_violin(data = box_data, aes(ova_fc, cell_type2), fill = "#f0f0f0", color = "#f0f0f0", size = 0.2) +
  geom_errorbarh(aes(xmin = lower, xmax = upper, alpha = conf, size = conf), height = 0) +
  # geom_errorbarh(aes(xmin = lower, xmax = upper, alpha = conf), height = 0, size = 3) +
  
  geom_point(shape = 22, size = 1, fill = "white") +
  scale_color_manual(values = type_cols, guide = F) +
  scale_alpha_manual(values = conf_alphas, guide = F) +
  scale_size_manual(
    name   = "Confidence Level",
    values = conf_sizes,
    guide  = guide_legend(direction = "horizontal", title.position = "top", label.position = "bottom")
  ) +
  scale_x_log10() +
  labs(x = "ova_fc") +
  theme_info +
  theme(
    legend.position       = c(1, 0.01),
    legend.justification  = c(1, 0),
    legend.title          = element_text(size = 10),
    legend.text           = element_text(size = 10),
    
    legend.key.height     = grid::unit(7, "pt"),
    legend.key.width      = grid::unit(20, "pt"),
    legend.spacing.x      = grid::unit(7, "pt"),
    legend.spacing.y      = grid::unit(3.5, "pt"),
    legend.box.background = element_rect(fill = "white", color = NA),
    legend.box.spacing    = grid::unit(0, "pt"),
    legend.title.align    = 0.5,
    axis.title.y          = element_blank()
  )

```

```{r "{{.x}} FIG", fig.width = 10, fig.height = 13, echo = F}

# Create final figure
plot_grid(
  gg1, gg2, gg3, gg4, gg5, gg6,
  ncol  = 2,
  align = "vh",
  axis  = "trbl"
)

```



```{r, "{{.x}} LEAST-SQUARED MEAN", echo = F, eval = F}

# Create data.frame with confidence intervals
fit <- box_data %>%
  lm(ova_fc ~ cell_type2, data = .)

conf_df <- tibble(level = c(0.99, 0.95, 0.8)) %>%
  mutate(df = map(level, ~ tidy(emmeans(fit, ~ cell_type2, options = list(level = .x))))) %>%
  unnest(cols = df) %>%
  dplyr::select(-df) %>%
  mutate(
    level = paste0(signif(100 * level, 2), "%"),
    cell_type2 = fct_reorder(cell_type2, estimate)
  )

# Set confidence colors and sizes
conf_cols <- c(
  `80%` = desaturate(darken("#0072B2", .2), .3),
  `95%` = desaturate(lighten("#0072B2", .2), .3),
  `99%` = desaturate(lighten("#0072B2", .4), .3)
)

conf_sizes <- c(
  `80%` = 3,
  `95%` = 2,
  `99%` = 1
)

conf_alphas <- c(
  `80%` = 1,
  `95%` = 0.5,
  `99%` = 0.25
)

# Create scaled error bars
gg6 <- conf_df %>%
  ggplot(aes(estimate, cell_type2, color = cell_type2)) +
  geom_errorbarh(aes(xmin = conf.low, xmax = conf.high, size = level, alpha = level), height = 0) +
  geom_point(data = filter(conf_df, level == "80%"), shape = 21, size = 1.5, fill = "white") +
  scale_color_manual(values = type_cols, guide = F) +
  scale_alpha_manual(values = conf_alphas, guide = F) +
  scale_size_manual(
    name   = "confidence level",
    values = conf_sizes,
    guide  = guide_legend(direction = "horizontal", title.position = "top", label.position = "bottom")
  ) +
  labs(x = "ova_fc") +
  theme_info +
  theme(
    legend.position       = c(1, 0.01),
    legend.justification  = c(1, 0),
    legend.key.height     = grid::unit(7, "pt"),
    legend.key.width      = grid::unit(35, "pt"),
    legend.spacing.x      = grid::unit(7, "pt"),
    legend.spacing.y      = grid::unit(3.5, "pt"),
    legend.box.background = element_rect(fill = "white", color = NA),
    legend.box.spacing    = grid::unit(0, "pt"),
    legend.title.align    = 0.5,
    axis.title.y          = element_blank()
  )

```

```{r, "{{.x}} CONFIDENCE INTERVALS", echo = F, eval = F}

my_data <- sobj %>% FetchData("adt_ovalbumin")

# rsample
x <- my_data %>% bootstraps()

x$splits %>%
  map_dbl(~ {
    .x %>%
      as_tibble() %>% 
      pull(adt_ovalbumin) %>% 
      median()
  })

# boots
boot_obj <- boot(
  data = my_data$adt_ovalbumin,
  statistic = function(x, i) median(x[i]),
  R = 10000
)

conf <- c(0.8, 0.9, 0.95)
names(conf) <- conf

conf_int <- conf %>%
  map(~ {
    res <- boot.ci(boot_obj, .x, "basic")
    res$basic[4:5]
  })

# wilcox.test
conf <- c(0.8, 0.9, 0.95)

conf %>%
  map(~ {
    wilcox.test(
      my_data$adt_ovalbumin,
      alternative = "less",
      correct     = TRUE,
      conf.int    = TRUE,
      conf.level  = .x
    ) %>%
      tidy() %>%
      mutate(conf = .x)
  }) %>%
  bind_rows()


```

```{r, ref.label = c("BOXES", "BARS", "FIG"), eval = F}
```

```{r "{{.x}} EXTRA PLOTS", echo = F, eval = F}

# Simple boxes
# box_data %>%
#   ggplot(aes(cell_type2, ova_fc, color = cell_type2, fill = cell_type2)) +
#   geom_sina(size = 0.5, color = "#d9d9d9") +
#   geom_boxplot(size = 0, outlier.shape = NA, width = 0.4) +
#   stat_summary(fun = "median", geom = "point", shape = 22, size = 1.5, fill = "white") +
#   scale_color_manual(values = type_cols) +
#   scale_fill_manual(values = type_cols) +
#   coord_flip() + 
#   scale_y_log10() + 
#   theme_info + 
#   theme(
#     legend.position = "none",
#     axis.title.y = element_blank()
#   )

# geom_sina
# box_data %>%
#   ggplot(aes(cell_type2, ova_fc, color = cell_type2)) +
#   geom_sina(size = 0.5) +
#   scale_color_manual(values = type_cols) +
#   coord_flip() +
#   scale_y_log10() +
#   theme_info +
#   theme(legend.position = "none")

# geom_quasirandom
# box_data %>%
#   ggplot(aes(cell_type2, ova_fc, color = cell_type2)) +
#   geom_quasirandom(size = 0.5) +
#   scale_color_manual(values = type_cols) +
#   coord_flip() +
#   scale_y_log10() +
#   theme_info +
#   theme(legend.position = "none")

# Error bars with beeswarm
# conf_df %>%
#   ggplot(aes(cell_type2, estimate, color = cell_type2)) +
#   geom_quasirandom(data = box_data, aes(cell_type2, ova_fc), size = 0.25, color = "#f9f9f9") +
#   geom_errorbar(aes(ymin = conf.low, ymax = conf.high, size = level, alpha = level), width = 0) +
#   geom_point(data = filter(conf_df, level == "80%"), shape = 22, size = 2, fill = "white") +
#   scale_color_manual(values = type_cols, guide = F) +
#   scale_alpha_manual(values = conf_alphas, guide = F) +
#   scale_size_manual(
#     name   = "confidence level",
#     values = conf_sizes,
#     guide  = guide_legend(direction = "horizontal", title.position = "top", label.position = "bottom")
#   ) +
#   scale_y_log10() +
#   coord_flip() +
#   labs(x = "ova_fc") +
#   theme_info +
#   theme(
#     legend.position       = c(1, 0.01),
#     legend.justification  = c(1, 0),
#     legend.key.height     = grid::unit(7, "pt"),
#     legend.key.width      = grid::unit(35, "pt"),
#     legend.spacing.x      = grid::unit(7, "pt"),
#     legend.spacing.y      = grid::unit(3.5, "pt"),
#     legend.box.background = element_rect(fill = "white", color = NA),
#     legend.box.spacing    = grid::unit(0, "pt"),
#     legend.title.align    = 0.5,
#     axis.title.y          = element_blank()
#   )

```

```{r, echo = F, eval = F}

# Create data.frame with confidence intervals
fit <- box_data %>%
  lm(ova_fc ~ cell_type2, data = .)

conf_df <- tibble(level = c(0.99, 0.95, 0.8)) %>%
  mutate(df = map(level, ~ tidy(emmeans(fit, ~ cell_type2, options = list(level = .x))))) %>%
  unnest(cols = df) %>%
  dplyr::select(-df) %>%
  mutate(
    level = paste0(signif(100 * level, 2), "%"),
    cell_type2 = fct_reorder(cell_type2, estimate)
  )

# Set confidence colors and sizes
conf_cols <- c(
  `80%` = desaturate(darken("#0072B2", .2), .3),
  `95%` = desaturate(lighten("#0072B2", .2), .3),
  `99%` = desaturate(lighten("#0072B2", .4), .3)
)

conf_sizes <- c(
  `80%` = 2.25,
  `95%` = 1.5,
  `99%` = 0.75
)

# Create scaled error bars
conf_df %>%
  ggplot(aes(estimate, cell_type2)) +
  geom_errorbarh(aes(xmin = conf.low, xmax = conf.high, color = level, size = level), height = 0) +
  geom_errorbarh(aes(xmin = conf.low, xmax = conf.high, color = level), height = 0) +
  geom_point(data = filter(conf_df, level == "80%"), size = 2.5, color = "#D55E00") +
  scale_color_manual(
    name   = "confidence level",
    values = conf_cols,
    guide  = guide_legend(direction = "horizontal", title.position = "top", label.position = "bottom")
  ) +
  scale_size_manual(
    name   = "confidence level", 
    values = conf_sizes,
    guide  = guide_legend(direction = "horizontal", title.position = "top", label.position = "bottom")
  ) +
  labs(x = "ova_fc") +
  theme_info +
  theme(
    legend.position       = c(1, 0.01),
    legend.justification  = c(1, 0),
    legend.key.height     = grid::unit(7, "pt"),
    legend.key.width      = grid::unit(35, "pt"),
    legend.spacing.x      = grid::unit(7, "pt"),
    legend.spacing.y      = grid::unit(3.5, "pt"),
    legend.box.background = element_rect(fill = "white", color = NA),
    legend.box.spacing    = grid::unit(0, "pt"),
    legend.title.align    = 0.5,
    axis.title.y          = element_blank()
  )

```




